'use client'

import React, { createContext, useContext, useState, ReactNode } from 'react'
import Confetti from 'react-confetti'

type Language = 'en' | 'es'

interface Translations {
  [key: string]: {
    [key: string]: string
  }
}

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Translations = {
  en: {
    'we.say': 'We are getting married!',
    'view.details': 'View Details',
    'rsvp': 'RSVP',
    'language': 'Language',
    'nav.home': 'Home',
    'nav.details': 'Details',
    'nav.story': 'Our Story',
    'nav.rsvp': 'RSVP',
    'nav.faqs': 'FAQs',
    'wedding.details': 'We await you at...',
    'wedding.subtitle': 'La Cúpula of the Finca Miravalle',
    'ceremony': 'Ceremony',
    'cocktail': 'Cocktail Hour',
    'dinner': 'Dinner & Dancing',
    'church.name': 'Iglesia de San Jerónimo el Real',
    'ceremony.description': 'Join us as we exchange vows in this historic church in the heart of Madrid.',
    'cocktail.description': 'Enjoy Spanish wines and tapas while we take photos.',
    'dinner.description': 'Celebrate with us over a traditional Spanish feast and dance the night away.',
    'weather.title': 'October Weather in Madrid',
    'weather.temp': 'Average temperature: 15-20°C (59-68°F)',
    'weather.rain': 'Low chance of rain',
    'weather.perfect': 'Perfect autumn weather for an outdoor celebration',
    'dress.code': 'Dress Code',
    'dress.formal': 'Formal attire',
    'dress.colors': 'We encourage autumn colors: burgundy, olive, navy, gold',
    'dress.shoes': 'Consider comfortable shoes for dancing!',
    'getting.around': 'Getting Around',
    'metro.info': 'Metro: Both venues are accessible via Madrid\'s excellent metro system',
    'taxi.info': 'Taxi: We recommend using official Madrid taxis or ride-sharing apps',
    'walking.info': 'Walking: The venues are within walking distance of many central hotels',
    'transport.note': 'Detailed transportation information will be provided closer to the date',
    'our.story': 'Our Story',
    'story.continue': 'And so the adventure continues...',
    'story.first.meeting.date': 'Summer 2020',
    'story.first.meeting.title': 'First Meeting',
    'story.first.meeting.desc': 'We met at a cozy café in Madrid, where our love story began over coffee and conversation.',
    'story.first.trip.date': 'Autumn 2020',
    'story.first.trip.title': 'First Trip Together',
    'story.first.trip.desc': 'Exploring the charming streets of Barcelona, discovering our shared love for travel and adventure.',
    'story.moving.date': 'Spring 2021',
    'story.moving.title': 'Moving In Together',
    'story.moving.desc': 'Starting our life together in a beautiful apartment in the heart of Madrid.',
    'story.proposal.date': 'Summer 2023',
    'story.proposal.title': 'The Proposal',
    'story.proposal.desc': 'A romantic evening at the Royal Palace, where Pablo got down on one knee under the stars.',
    'schedule.title': 'Itinerary',
    'schedule.departure': 'Departure Bus',
    'schedule.departure.location': 'Meeting Point',
    'schedule.departure.description': 'Hop aboard and let\'s roll!',
    'schedule.guest.reception': 'Guest Reception',
    'schedule.guest.reception.location': 'Reception Area',
    'schedule.guest.reception.description': 'Welcome drinks and mingling with fellow guests!',
    'schedule.ceremony': 'Ceremony',
    'schedule.ceremony.location': 'Ceremony Venue',
    'schedule.ceremony.description': 'Witness the \'I do\'s\' under the golden sun ✨',
    'schedule.cocktail': 'Cocktail',
    'schedule.cocktail.location': 'Cocktail Area',
    'schedule.cocktail.description': 'Time to sip, laugh, and celebrate!',
    'schedule.banquet': 'Banquet',
    'schedule.banquet.location': 'Dining Hall',
    'schedule.banquet.description': 'Feast time with laughter and speeches!',
    'schedule.party': 'Party',
    'schedule.party.location': 'Dance Floor',
    'schedule.party.description': 'Dance like nobody\'s watching!',
    'schedule.return': 'Return Bus',
    'schedule.return.location': 'Departure Point',
    'schedule.return.description': 'Back to reality — with full hearts!',
    'schedule.subtitle': "So you don't miss a thing",
    'wedding.date': 'October 18, 2025',
    'rsvp.title': 'RSVP',
    'rsvp.subtitle': 'Please let us know if you can join us on our special day',
    'rsvp.subtitle.line1': 'One per person, so no one gets lost!',
    'rsvp.subtitle.line2': 'Accompanying guests also need to fill out the form.',
    'rsvp.full.name': 'Full Name',
    'rsvp.full.name.placeholder': 'Enter your full name',
    'rsvp.attending': 'Will you be joining us on this special day?',
    'rsvp.attending.yes': 'Of course, I wouldn\'t miss it for anything!',
    'rsvp.attending.no': 'I can\'t make it, but I\'ll celebrate from afar.',
    'rsvp.transport': 'Will you go on your own or would you like us to reserve a seat on the bus?',
    'rsvp.transport.own': 'I\'ll go on my own.',
    'rsvp.transport.bus': 'Party bus, please! Reserve me a seat.',
    'rsvp.dietary': 'Do you have any allergies, intolerances, or special diet we should know about? We want to make sure everyone can enjoy the food.',
    'rsvp.dietary.placeholder': 'Enter any dietary restrictions or leave blank if none',
    'rsvp.song': 'What song would you definitely like to hear at the party?',
    'rsvp.song.placeholder': 'Enter your song request or leave blank if none',
    'rsvp.extra': 'Last question, we promise! Anything else you want to tell us, ask, or confess before the wedding?',
    'rsvp.extra.placeholder': 'Enter any additional information or leave blank if none',
    'rsvp.submit': 'Send',
    'rsvp.thanks.yes': 'Thank you for your RSVP!',
    'rsvp.thanks.no': 'We\'re sorry you can\'t make it',
    'rsvp.miss.you': 'We\'ll miss you!',
    'faqs.title': 'Frequently Asked Questions',
    'faqs.travel.title': 'Travel & Accommodation',
    'faqs.travel.airport': 'Which airport should I fly into?',
    'faqs.travel.airport.answer': 'Madrid-Barajas Airport (MAD) is the main international airport, located just 12km from the city center. It\'s easily accessible by metro, bus, or taxi.',
    'faqs.travel.hotel': 'Where should I stay?',
    'faqs.travel.hotel.answer': 'We recommend staying in the city center, particularly in neighborhoods like Salamanca, Retiro, or Centro. We\'ve arranged special rates at Hotel Wellington and NH Collection Madrid Suecia - booking details will be sent via email.',
    'faqs.travel.transport': 'How do I get around Madrid?',
    'faqs.travel.transport.answer': 'Madrid has an excellent public transportation system. The metro is clean, safe, and efficient. Taxis and ride-sharing services are also readily available. Most attractions are within walking distance if you\'re staying in the city center.',
    'faqs.wedding.arrival': 'What time should I arrive at the ceremony?',
    'faqs.wedding.arrival.answer': 'Please arrive at least 15 minutes before the ceremony starts at 16:00. This will give you time to be seated and greet other guests.',
    'faqs.wedding.dress': 'What\'s the dress code?',
    'faqs.wedding.dress.answer': 'The dress code is formal. We encourage autumn colors like burgundy, olive, navy, and gold. The evening can get cool, so consider bringing a light jacket or wrap.',
    'faqs.wedding.photos': 'Can I take photos during the ceremony?',
    'faqs.wedding.photos.answer': 'We kindly ask that you refrain from taking photos during the ceremony - we have professional photographers to capture these moments. Feel free to take photos during the reception!',
    'faqs.madrid.sights': 'What should I see in Madrid?',
    'faqs.madrid.sights.answer': 'Don\'t miss the Prado Museum, Retiro Park, Royal Palace, and Plaza Mayor. For food lovers, the San Miguel Market is a must-visit. We\'ll provide a detailed guide of our favorite spots!',
    'faqs.day.trips': 'Any day trip recommendations?',
    'faqs.day.trips.answer': 'Toledo and Segovia are beautiful historic cities just an hour from Madrid. Both make perfect day trips and are accessible by high-speed train.',
    'faqs.tapas': 'Where are the best tapas spots?',
    'faqs.tapas.answer': 'La Latina neighborhood is famous for its tapas bars. Some of our favorites include Casa Lucio, La Casa del Abuelo, and Lateral. Don\'t miss churros at San Ginés!',
    'faqs.still.questions': 'Still have questions?',
    'faqs.contact.us': 'Contact us at wedding@example.com',
    'footer.contactInfo': 'Contact info',
    'footer.heading': 'WE AWAIT YOU',
    'footer.copyright': '© 2025. Made with love by Miriam & Pablo ❤️'
  },
  es: {
    'we.say': '¡Nos casamos!',
    'view.details': 'Ver Detalles',
    'rsvp': 'Confirmar Asistencia',
    'language': 'Idioma',
    'nav.home': 'Inicio',
    'nav.details': 'Detalles',
    'nav.story': 'Nuestra Historia',
    'nav.rsvp': 'Confirmar',
    'nav.faqs': 'Preguntas Frecuentes',
    'wedding.details': 'Te esperamos en...',
    'wedding.subtitle': 'La Cúpula de la Finca Miravalle',
    'ceremony': 'Ceremonia',
    'cocktail': 'Cóctel',
    'dinner': 'Cena y Baile',
    'church.name': 'Iglesia de San Jerónimo el Real',
    'ceremony.description': 'Acompáñanos mientras intercambiamos votos en esta histórica iglesia en el corazón de Madrid.',
    'cocktail.description': 'Disfruta de vinos españoles y tapas mientras nos hacemos las fotos.',
    'dinner.description': 'Celebra con nosotros con un festín tradicional español y baila toda la noche.',
    'weather.title': 'Clima de Octubre en Madrid',
    'weather.temp': 'Temperatura media: 15-20°C',
    'weather.rain': 'Baja probabilidad de lluvia',
    'weather.perfect': 'Clima perfecto de otoño para una celebración al aire libre',
    'dress.code': 'Código de Vestimenta',
    'dress.formal': 'Vestimenta formal',
    'dress.colors': 'Sugerimos colores de otoño: burgundy, oliva, azul marino, dorado',
    'dress.shoes': '¡Considera zapatos cómodos para bailar!',
    'getting.around': 'Cómo Llegar',
    'metro.info': 'Metro: Ambas sedes son accesibles a través del excelente sistema de metro de Madrid',
    'taxi.info': 'Taxi: Recomendamos usar taxis oficiales de Madrid o aplicaciones de transporte',
    'walking.info': 'A pie: Las sedes están a poca distancia de muchos hoteles céntricos',
    'transport.note': 'Información detallada de transporte se proporcionará más cerca de la fecha',
    'our.story': 'Nuestra Historia',
    'story.continue': 'Y así continúa la aventura...',
    'story.first.meeting.date': 'Verano 2020',
    'story.first.meeting.title': 'Primer Encuentro',
    'story.first.meeting.desc': 'Nos conocimos en un acogedor café en Madrid, donde nuestra historia de amor comenzó sobre café y conversación.',
    'story.first.trip.date': 'Otoño 2020',
    'story.first.trip.title': 'Primer Viaje Juntos',
    'story.first.trip.desc': 'Explorando las encantadoras calles de Barcelona, descubriendo nuestro amor compartido por los viajes y la aventura.',
    'story.moving.date': 'Primavera 2021',
    'story.moving.title': 'Vivir Juntos',
    'story.moving.desc': 'Comenzando nuestra vida juntos en un hermoso apartamento en el corazón de Madrid.',
    'story.proposal.date': 'Verano 2023',
    'story.proposal.title': 'La Propuesta',
    'story.proposal.desc': 'Una romántica velada en el Palacio Real, donde Pablo se arrodilló bajo las estrellas.',
    'schedule.title': 'Itinerario',
    'schedule.departure': 'Autocar de Ida',
    'schedule.departure.location': 'Punto de Encuentro',
    'schedule.departure.description': '¡Sube al autocar y empecemos el viaje!',
    'schedule.guest.reception': 'Recepción de Invitados',
    'schedule.guest.reception.location': 'Área de Recepción',
    'schedule.guest.reception.description': 'Bienvenida y mezclándonos con otros invitados!',
    'schedule.ceremony': 'Ceremonia',
    'schedule.ceremony.location': 'Lugar de la Ceremonia',
    'schedule.ceremony.description': 'Presencia los \'Sí, quiero\' bajo el sol dorado ✨',
    'schedule.cocktail': 'Cóctel',
    'schedule.cocktail.location': 'Zona de Cócteles',
    'schedule.cocktail.description': '¡Hora de brindar, reír y celebrar!',
    'schedule.banquet': 'Banquete',
    'schedule.banquet.location': 'Salón de Banquetes',
    'schedule.banquet.description': '¡Hora de festejar con risas y discursos!',
    'schedule.party': 'Fiesta',
    'schedule.party.location': 'Pista de Baile',
    'schedule.party.description': '¡Baila como si nadie te estuviera mirando!',
    'schedule.return': 'Autocar de Vuelta',
    'schedule.return.location': 'Punto de Salida',
    'schedule.return.description': 'De vuelta a la realidad — ¡con el corazón lleno!',
    'schedule.subtitle': 'Para que no te pierdas nada',
    'wedding.date': '18 de octubre de 2025',
    'rsvp.title': 'Confirmar Asistencia',
    'rsvp.subtitle': 'Por favor, indícanos si podrás acompañarnos en nuestro día especial',
    'rsvp.subtitle.line1': 'Uno por cabeza, ¡que nadie se nos pierda!',
    'rsvp.subtitle.line2': 'Los acompañantes también tienen que rellenar el formulario.',
    'rsvp.full.name': 'Nombre completo',
    'rsvp.full.name.placeholder': 'Introduce tu nombre completo',
    'rsvp.attending': '¿Nos acompañarás en este día tan especial?',
    'rsvp.attending.yes': 'Claro que sí, ¡no me lo perdería por nada!',
    'rsvp.attending.no': 'No podré ir, pero celebraré desde lejos.',
    'rsvp.transport': '¿Vas por tu cuenta o quieres que te reservemos asiento en el bus?',
    'rsvp.transport.own': 'Iré por mi cuenta.',
    'rsvp.transport.bus': '¡Party bus, por favor! Reservadme un asiento.',
    'rsvp.dietary': '¿Tienes alguna alergia, intolerancia o dieta especial que debamos saber? Nos queremos asegurar de que todos podamos disfrutar de la comida.',
    'rsvp.dietary.placeholder': 'Introduce cualquier restricción alimentaria o déjalo en blanco si no hay ninguna',
    'rsvp.song': '¿Qué canción te gustaría que sonara en la fiesta sí o sí?',
    'rsvp.song.placeholder': 'Introduce tu canción o déjalo en blanco si no hay ninguna',
    'rsvp.extra': '¡Última pregunta, lo prometemos! ¿Algo más que quieras contarnos, pedir o confesar antes de la boda?',
    'rsvp.extra.placeholder': 'Introduce cualquier información adicional o déjalo en blanco si no hay ninguna',
    'rsvp.submit': 'Enviar',
    'rsvp.thanks.yes': '¡Gracias por tu confirmación!',
    'rsvp.thanks.no': 'Lamentamos que no puedas acompañarnos',
    'rsvp.miss.you': '¡Te echaremos de menos!',
    'faqs.title': 'Preguntas Frecuentes',
    'faqs.travel.title': 'Viaje y Alojamiento',
    'faqs.travel.airport': '¿A qué aeropuerto debo volar?',
    'faqs.travel.airport.answer': 'El Aeropuerto Madrid-Barajas (MAD) es el principal aeropuerto internacional, ubicado a solo 12km del centro de la ciudad. Es fácilmente accesible en metro, autobús o taxi.',
    'faqs.travel.hotel': '¿Dónde debería hospedarme?',
    'faqs.travel.hotel.answer': 'Recomendamos alojarse en el centro de la ciudad, particularmente en barrios como Salamanca, Retiro o Centro. Hemos organizado tarifas especiales en el Hotel Wellington y NH Collection Madrid Suecia - los detalles de reserva se enviarán por correo electrónico.',
    'faqs.travel.transport': '¿Cómo me muevo por Madrid?',
    'faqs.travel.transport.answer': 'Madrid tiene un excelente sistema de transporte público. El metro es limpio, seguro y eficiente. Los taxis y servicios de transporte compartido también están fácilmente disponibles. La mayoría de las atracciones están a poca distancia si te alojas en el centro.',
    'faqs.wedding.arrival': '¿A qué hora debo llegar a la ceremonia?',
    'faqs.wedding.arrival.answer': 'Por favor, llega al menos 15 minutos antes de que comience la ceremonia a las 16:00. Esto te dará tiempo para sentarte y saludar a otros invitados.',
    'faqs.wedding.dress': '¿Cuál es el código de vestimenta?',
    'faqs.wedding.dress.answer': 'El código de vestimenta es formal. Sugerimos colores de otoño como burdeos, oliva, azul marino y dorado. La noche puede refrescar, así que considera llevar una chaqueta o chal ligero.',
    'faqs.wedding.photos': '¿Puedo tomar fotos durante la ceremonia?',
    'faqs.wedding.photos.answer': 'Amablemente les pedimos que se abstengan de tomar fotos durante la ceremonia - tenemos fotógrafos profesionales para capturar estos momentos. ¡Siéntete libre de tomar fotos durante la recepción!',
    'faqs.madrid.sights': '¿Qué debería ver en Madrid?',
    'faqs.madrid.sights.answer': 'No te pierdas el Museo del Prado, el Parque del Retiro, el Palacio Real y la Plaza Mayor. Para los amantes de la comida, el Mercado de San Miguel es una visita obligada. ¡Te proporcionaremos una guía detallada de nuestros lugares favoritos!',
    'faqs.day.trips': '¿Recomendaciones para excursiones de un día?',
    'faqs.day.trips.answer': 'Toledo y Segovia son hermosas ciudades históricas a solo una hora de Madrid. Ambas son excursiones perfectas de un día y son accesibles en tren de alta velocidad.',
    'faqs.tapas': '¿Dónde están los mejores bares de tapas?',
    'faqs.tapas.answer': 'El barrio de La Latina es famoso por sus bares de tapas. Algunos de nuestros favoritos incluyen Casa Lucio, La Casa del Abuelo y Lateral. ¡No te pierdas los churros en San Ginés!',
    'faqs.still.questions': '¿Aún tienes preguntas?',
    'faqs.contact.us': 'Contáctanos en wedding@example.com',
    'footer.contactInfo': 'Información de Contacto',
    'footer.heading': 'TE ESPERAMOS',
    'footer.copyright': '© 2025. Hecho con amor por Miriam & Pablo ❤️'
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es')
  const [isAttending, setIsAttending] = useState(false)

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
      {isAttending && <Confetti />}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
} 